# Generated by Django 2.1.2 on 2020-02-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, max_length=15, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dept_name', models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructors', to='acad.Department')),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('sec_id', models.CharField(max_length=8)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('building', models.CharField(blank=True, max_length=15, null=True)),
                ('room_number', models.CharField(blank=True, max_length=7, null=True)),
                ('time_slot_id', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('tot_cred', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('dept_name', models.ForeignKey(blank=True, db_column='dept_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='acad.Department')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acad.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='takes', to='acad.Student')),
            ],
            options={
                'db_table': 'takes',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teaches', to='acad.Instructor')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acad.Section')),
            ],
            options={
                'db_table': 'teaches',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ManyToManyField(related_name='taken_by', through='acad.Takes', to='acad.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_id', 'sec_id', 'year', 'semester')},
        ),
        migrations.AddField(
            model_name='instructor',
            name='section',
            field=models.ManyToManyField(related_name='taught_by', through='acad.Teaches', to='acad.Section'),
        ),
    ]
